# Generated by Django 2.2.4 on 2020-06-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200609_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('PB', 'Published'), ('WD', 'Withdrawn'), ('DF', 'Draft')], default=' ', max_length=2),
        ),
    ]
