# Generated by Django 2.2.4 on 2020-06-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('desc', models.TextField(default='')),
                ('img', models.ImageField(default='author_image/default.png', upload_to='author_image/')),
            ],
        ),
    ]
